package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessEventFindings implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BusinessEventFindings() {
    }




}