package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessEventFindings implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.brimmatech.businesseventrules.LoanFields loanFields;

	private com.brimmatech.businesseventrules.BusinessEventFindings businessEventFindings;

	private com.brimmatech.businesseventrules.LoanData loanData;

	public BusinessEventFindings() {
	}

	public com.brimmatech.businesseventrules.LoanFields getLoanFields() {
		return this.loanFields;
	}

	public void setLoanFields(
			com.brimmatech.businesseventrules.LoanFields loanFields) {
		this.loanFields = loanFields;
	}

	public com.brimmatech.businesseventrules.BusinessEventFindings getBusinessEventFindings() {
		return this.businessEventFindings;
	}

	public void setBusinessEventFindings(
			com.brimmatech.businesseventrules.BusinessEventFindings businessEventFindings) {
		this.businessEventFindings = businessEventFindings;
	}

	public com.brimmatech.businesseventrules.LoanData getLoanData() {
		return this.loanData;
	}

	public void setLoanData(com.brimmatech.businesseventrules.LoanData loanData) {
		this.loanData = loanData;
	}

	public BusinessEventFindings(
			com.brimmatech.businesseventrules.LoanFields loanFields,
			com.brimmatech.businesseventrules.BusinessEventFindings businessEventFindings,
			com.brimmatech.businesseventrules.LoanData loanData) {
		this.loanFields = loanFields;
		this.businessEventFindings = businessEventFindings;
		this.loanData = loanData;
	}

}