package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessEventFindings implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.brimmatech.businesseventrules.LoanFields loanFields;

	public BusinessEventFindings() {
	}

	public com.brimmatech.businesseventrules.LoanFields getLoanFields() {
		return this.loanFields;
	}

	public void setLoanFields(
			com.brimmatech.businesseventrules.LoanFields loanFields) {
		this.loanFields = loanFields;
	}

	public BusinessEventFindings(
			com.brimmatech.businesseventrules.LoanFields loanFields) {
		this.loanFields = loanFields;
	}

}