package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditOrderTracking implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer id;
	private Integer folderId;

	public CreditOrderTracking() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getFolderId() {
		return this.folderId;
	}

	public void setFolderId(java.lang.Integer folderId) {
		this.folderId = folderId;
	}

	public CreditOrderTracking(java.lang.Integer id, java.lang.Integer folderId) {
		this.id = id;
		this.folderId = folderId;
	}

}