package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanField implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LoanField() {
    }




}