package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private LoanData loanData;
	private java.util.List<LoanData> loanDataList;

	public LoanDto() {
	}

	public LoanData getLoanData() {
		return this.loanData;
	}

	public void setLoanData(LoanData loanData) {
		this.loanData = loanData;
	}

	public java.util.List<LoanData> getLoanDataList() {
		return this.loanDataList;
	}

	public void setLoanDataList(
			java.util.List<LoanData> loanDataList) {
		this.loanDataList = loanDataList;
	}

	public LoanDto(
			LoanData loanData,
			java.util.List<LoanData> loanDataList) {
		this.loanData = loanData;
		this.loanDataList = loanDataList;
	}

}