package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class LoanData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String loanId;

	public LoanData() {
	}

	public java.lang.String getLoanId() {
		return this.loanId;
	}

	public void setLoanId(java.lang.String loanId) {
		this.loanId = loanId;
	}

	public LoanData(java.lang.String loanId) {
		this.loanId = loanId;
	}

}