package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleValidationResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RuleValidationResult() {
    }




}