package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RulesData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ruleName;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> ruleDataList;

	public RulesData() {
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}

	public java.util.List<java.lang.String> getRuleDataList() {
		return this.ruleDataList;
	}

	public void setRuleDataList(java.util.List<java.lang.String> ruleDataList) {
		this.ruleDataList = ruleDataList;
	}

	public RulesData(java.lang.String ruleName,
			java.util.List<java.lang.String> ruleDataList) {
		this.ruleName = ruleName;
		this.ruleDataList = ruleDataList;
	}

}