package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RulesDataDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.brimmatech.businesseventrules.RulesData> rulesDataList;

	public RulesDataDto() {
	}

	public java.util.List<com.brimmatech.businesseventrules.RulesData> getRulesDataList() {
		return this.rulesDataList;
	}

	public void setRulesDataList(
			java.util.List<com.brimmatech.businesseventrules.RulesData> rulesDataList) {
		this.rulesDataList = rulesDataList;
	}

	public RulesDataDto(
			java.util.List<com.brimmatech.businesseventrules.RulesData> rulesDataList) {
		this.rulesDataList = rulesDataList;
	}

}