package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleValidationResults implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResultList;

	public RuleValidationResults() {
	}

	public java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> getRuleValidationResultList() {
		return this.ruleValidationResultList;
	}

	public void setRuleValidationResultList(
			java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResultList) {
		this.ruleValidationResultList = ruleValidationResultList;
	}

	public RuleValidationResults(
			java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResultList) {
		this.ruleValidationResultList = ruleValidationResultList;
	}

}