package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleValidationResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ruleId;
	private boolean validationResult;

	public RuleValidationResult() {
	}

	public java.lang.String getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(java.lang.String ruleId) {
		this.ruleId = ruleId;
	}

	public boolean isValidationResult() {
		return this.validationResult;
	}

	public void setValidationResult(boolean validationResult) {
		this.validationResult = validationResult;
	}

	public RuleValidationResult(java.lang.String ruleId,
			boolean validationResult) {
		this.ruleId = ruleId;
		this.validationResult = validationResult;
	}

}