package com.brimmatech.businesseventrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleValidationResults implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResult;

	public RuleValidationResults() {
	}

	public java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> getRuleValidationResult() {
		return this.ruleValidationResult;
	}

	public void setRuleValidationResult(
			java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResult) {
		this.ruleValidationResult = ruleValidationResult;
	}

	public RuleValidationResults(
			java.util.List<com.brimmatech.businesseventrules.RuleValidationResult> ruleValidationResult) {
		this.ruleValidationResult = ruleValidationResult;
	}

}