package com.brimmatech.businesseventrules;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Arrays;
import java.time.DayOfWeek;

function String retrieveFolderIdsForCreditDecision(RulesDataDto rulesDataDto, int days) {

    String validFolderIds = "";
    String applicationDate = "";
    String folderId = "";
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
    DateTimeFormatter withTimeFormatter = DateTimeFormatter.ofPattern("MM/dd/yyyy hh:mm:ssa");
    
    for (RulesData rulesData : rulesDataDto.getRulesDataList()) {
        String ruleName = rulesData.getRuleName();

        if ("CreditDecision".equals(ruleName)) {
            List<String> rulesDataList = rulesData.getRuleDataList();

            for (String ruleData : rulesDataList) {
                String[] keyValue = ruleData.split("\\|");

                if (keyValue.length == 2) {
                    String key = keyValue[0];
                    String value = keyValue[1];

                    if ("FolderId".equals(key)) {
                        folderId = value;
                    }
                    
                    if ("ApplicationDate".equals(key)) {
                        //applicationDate = value;
                        LocalDate parsedDate = null;

                        try {
                            parsedDate = LocalDate.parse(value, withTimeFormatter);
                        } catch (Exception e) {
                            parsedDate = LocalDate.parse(value, formatter);
                        }

                        applicationDate = parsedDate.format(formatter);
                    }
                }
                
                if (applicationDate.length() > 0 && folderId.length() > 0 
                    && isCreditDecisionDue(applicationDate, days, formatter)) {
                    
                    if (validFolderIds.length() > 0) {
                        validFolderIds += ",";
                    }
                    
                    validFolderIds += folderId;
                    folderId = "";
                    applicationDate = "";
                }
            }
        }
    }

    return validFolderIds;
}


function boolean isCreditDecisionDue(String applicationDate, int days, DateTimeFormatter formatter) {

    LocalDate start = LocalDate.parse(applicationDate, formatter);

    LocalDate end = start.plusDays(days);

    return end.isEqual(LocalDate.now());
}