package com.brimmatech.businesseventrules;

function String getLoanDataForTheBusinessEvent(LoanData loanData)
{
      if(loanData != null && loanData.getLoanId() != null)
      {
        return "true";
      }
      return "false";
}

function String validateCreditOrderTrackingCreditReferenceNumber(LoanData loanData)
{
    String isValid = "true";
    if(loanData != null &&
    loanData.getCreditOrderTracking() != null &&
    loanData.getCreditOrderTracking().getFolderId() != null &&
    loanData.getCreditOrderTracking().getCreditReferenceNumbers() != null)
    {
        isValid = "false";
    }
    return isValid;
}

function String validateRptFeesheetFolderId(LoanData loanData) 
{
    String isValid = "true";
    if(loanData != null && loanData.getRptFeeSheet() != null && loanData.getRptFeeSheet().getFolderId() != null)
    {
        isValid = "false";
        
    }
    return isValid;
}
